# Generated by Django 2.2.1 on 2019-06-01 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_symbol', models.CharField(help_text='Enter the Stock Symbol', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for particular Stock Symbol', primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-stock_symbol'],
            },
        ),
    ]
